namespace MvcPerfTest.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class InitialCreate : DbMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.Page1Model",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        TestId = c.Int(nullable: false),
                        Field1 = c.String(),
                        Field2 = c.String(),
                        Field3 = c.String(),
                        Field4 = c.String(),
                        Field5 = c.String(),
                        Field6 = c.String(),
                        Field7 = c.String(),
                        Field8 = c.String(),
                        Field9 = c.String(),
                        Field10 = c.String(),
                        Field11 = c.String(),
                        Field12 = c.String(),
                        Field13 = c.String(),
                        Field14 = c.String(),
                        Field15 = c.String(),
                        Field16 = c.String(),
                        Field17 = c.String(),
                        Field18 = c.String(),
                        Field19 = c.String(),
                        Field20 = c.String(),
                        Field21 = c.String(),
                        Field22 = c.String(),
                        Field23 = c.String(),
                        Field24 = c.String(),
                        Field25 = c.String(),
                        Field26 = c.String(),
                        Field27 = c.String(),
                        Field28 = c.String(),
                        Field29 = c.String(),
                        Field30 = c.String(),
                        Field31 = c.String(),
                        Field32 = c.String(),
                        Field33 = c.String(),
                        Field34 = c.String(),
                        Field35 = c.String(),
                        Field36 = c.String(),
                        Field37 = c.String(),
                        Field38 = c.String(),
                        Field39 = c.String(),
                        Field40 = c.String(),
                        Field41 = c.String(),
                        Field42 = c.String(),
                        Field43 = c.String(),
                        Field44 = c.String(),
                        Field45 = c.String(),
                        Field46 = c.String(),
                        Field47 = c.String(),
                        Field48 = c.String(),
                        Field49 = c.String(),
                        Field50 = c.String(),
                    })
                .PrimaryKey(t => t.Id);
            
            CreateTable(
                "dbo.Page2Model",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        TestId = c.Int(nullable: false),
                        Field1 = c.String(),
                        Field2 = c.String(),
                        Field3 = c.String(),
                        Field4 = c.String(),
                        Field5 = c.String(),
                        Field6 = c.String(),
                        Field7 = c.String(),
                        Field8 = c.String(),
                        Field9 = c.String(),
                        Field10 = c.String(),
                        Field11 = c.String(),
                        Field12 = c.String(),
                        Field13 = c.String(),
                        Field14 = c.String(),
                        Field15 = c.String(),
                        Field16 = c.String(),
                        Field17 = c.String(),
                        Field18 = c.String(),
                        Field19 = c.String(),
                        Field20 = c.String(),
                        Field21 = c.String(),
                        Field22 = c.String(),
                        Field23 = c.String(),
                        Field24 = c.String(),
                        Field25 = c.String(),
                        Field26 = c.String(),
                        Field27 = c.String(),
                        Field28 = c.String(),
                        Field29 = c.String(),
                        Field30 = c.String(),
                        Field31 = c.String(),
                        Field32 = c.String(),
                        Field33 = c.String(),
                        Field34 = c.String(),
                        Field35 = c.String(),
                        Field36 = c.String(),
                        Field37 = c.String(),
                        Field38 = c.String(),
                        Field39 = c.String(),
                        Field40 = c.String(),
                        Field41 = c.String(),
                        Field42 = c.String(),
                        Field43 = c.String(),
                        Field44 = c.String(),
                        Field45 = c.String(),
                        Field46 = c.String(),
                        Field47 = c.String(),
                        Field48 = c.String(),
                        Field49 = c.String(),
                        Field50 = c.String(),
                    })
                .PrimaryKey(t => t.Id);
            
            CreateTable(
                "dbo.Page3Model",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        TestId = c.Int(nullable: false),
                        Field1 = c.String(),
                        Field2 = c.String(),
                        Field3 = c.String(),
                        Field4 = c.String(),
                        Field5 = c.String(),
                        Field6 = c.String(),
                        Field7 = c.String(),
                        Field8 = c.String(),
                        Field9 = c.String(),
                        Field10 = c.String(),
                        Field11 = c.String(),
                        Field12 = c.String(),
                        Field13 = c.String(),
                        Field14 = c.String(),
                        Field15 = c.String(),
                        Field16 = c.String(),
                        Field17 = c.String(),
                        Field18 = c.String(),
                        Field19 = c.String(),
                        Field20 = c.String(),
                        Field21 = c.String(),
                        Field22 = c.String(),
                        Field23 = c.String(),
                        Field24 = c.String(),
                        Field25 = c.String(),
                        Field26 = c.String(),
                        Field27 = c.String(),
                        Field28 = c.String(),
                        Field29 = c.String(),
                        Field30 = c.String(),
                        Field31 = c.String(),
                        Field32 = c.String(),
                        Field33 = c.String(),
                        Field34 = c.String(),
                        Field35 = c.String(),
                        Field36 = c.String(),
                        Field37 = c.String(),
                        Field38 = c.String(),
                        Field39 = c.String(),
                        Field40 = c.String(),
                        Field41 = c.String(),
                        Field42 = c.String(),
                        Field43 = c.String(),
                        Field44 = c.String(),
                        Field45 = c.String(),
                        Field46 = c.String(),
                        Field47 = c.String(),
                        Field48 = c.String(),
                        Field49 = c.String(),
                        Field50 = c.String(),
                    })
                .PrimaryKey(t => t.Id);
            
            CreateTable(
                "dbo.Page4Model",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        TestId = c.Int(nullable: false),
                        Field1 = c.String(),
                        Field2 = c.String(),
                        Field3 = c.String(),
                        Field4 = c.String(),
                        Field5 = c.String(),
                        Field6 = c.String(),
                        Field7 = c.String(),
                        Field8 = c.String(),
                        Field9 = c.String(),
                        Field10 = c.String(),
                        Field11 = c.String(),
                        Field12 = c.String(),
                        Field13 = c.String(),
                        Field14 = c.String(),
                        Field15 = c.String(),
                        Field16 = c.String(),
                        Field17 = c.String(),
                        Field18 = c.String(),
                        Field19 = c.String(),
                        Field20 = c.String(),
                        Field21 = c.String(),
                        Field22 = c.String(),
                        Field23 = c.String(),
                        Field24 = c.String(),
                        Field25 = c.String(),
                        Field26 = c.String(),
                        Field27 = c.String(),
                        Field28 = c.String(),
                        Field29 = c.String(),
                        Field30 = c.String(),
                        Field31 = c.String(),
                        Field32 = c.String(),
                        Field33 = c.String(),
                        Field34 = c.String(),
                        Field35 = c.String(),
                        Field36 = c.String(),
                        Field37 = c.String(),
                        Field38 = c.String(),
                        Field39 = c.String(),
                        Field40 = c.String(),
                        Field41 = c.String(),
                        Field42 = c.String(),
                        Field43 = c.String(),
                        Field44 = c.String(),
                        Field45 = c.String(),
                        Field46 = c.String(),
                        Field47 = c.String(),
                        Field48 = c.String(),
                        Field49 = c.String(),
                        Field50 = c.String(),
                    })
                .PrimaryKey(t => t.Id);
            
            CreateTable(
                "dbo.Page5Model",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        TestId = c.Int(nullable: false),
                        Field1 = c.String(),
                        Field2 = c.String(),
                        Field3 = c.String(),
                        Field4 = c.String(),
                        Field5 = c.String(),
                        Field6 = c.String(),
                        Field7 = c.String(),
                        Field8 = c.String(),
                        Field9 = c.String(),
                        Field10 = c.String(),
                        Field11 = c.String(),
                        Field12 = c.String(),
                        Field13 = c.String(),
                        Field14 = c.String(),
                        Field15 = c.String(),
                        Field16 = c.String(),
                        Field17 = c.String(),
                        Field18 = c.String(),
                        Field19 = c.String(),
                        Field20 = c.String(),
                        Field21 = c.String(),
                        Field22 = c.String(),
                        Field23 = c.String(),
                        Field24 = c.String(),
                        Field25 = c.String(),
                        Field26 = c.String(),
                        Field27 = c.String(),
                        Field28 = c.String(),
                        Field29 = c.String(),
                        Field30 = c.String(),
                        Field31 = c.String(),
                        Field32 = c.String(),
                        Field33 = c.String(),
                        Field34 = c.String(),
                        Field35 = c.String(),
                        Field36 = c.String(),
                        Field37 = c.String(),
                        Field38 = c.String(),
                        Field39 = c.String(),
                        Field40 = c.String(),
                        Field41 = c.String(),
                        Field42 = c.String(),
                        Field43 = c.String(),
                        Field44 = c.String(),
                        Field45 = c.String(),
                        Field46 = c.String(),
                        Field47 = c.String(),
                        Field48 = c.String(),
                        Field49 = c.String(),
                        Field50 = c.String(),
                    })
                .PrimaryKey(t => t.Id);
            
        }
        
        public override void Down()
        {
            DropTable("dbo.Page5Model");
            DropTable("dbo.Page4Model");
            DropTable("dbo.Page3Model");
            DropTable("dbo.Page2Model");
            DropTable("dbo.Page1Model");
        }
    }
}
